language: haskell
notifications:
  email: false
before_script:
- cabal install --only-dependencies
- cabal configure --enable-tests
- cabal build
script:
- cabal test --show-details=always --test-options="--color"
